### PR TITLE
improve video generation

### PR DESCRIPTION
**Pull request by cjmayo**
Speed up by removing Python threading and solely using the signals emitted by gtkfractal.

Clarify that a video is made up of keyframes and transitions consisting of a number of frames defined by the duration parameter. By default the keyframe is shown for one frame but this is configurable using the stopped parameter.

---

Only the last commit is the new video work, all the others could go straight in. (it is based on the branch in #43).

One last issue, present in 4.0.1 too - does the blend function work? The sequence of transition frames seems to stop well short of the next keyframe?

### CODE REVIEW

**Comment by edyoung** [comment]
Would if be best to rebase ?

**Comment by cjmayo** [comment]
Rebased on master. Travis isn't working for me with `xvfb-run` locally either...

**Comment by cjmayo** [comment]
Still failing even with XAUTHORITY. I can't see the Travis logs so I'll stop guessing.

**Comment by cjmayo** [comment]
I had some of the Travis JavaScript blocked which was why I couldn't see the logs. I've put the necessary fixes in #47.
Then split the video fixes into #48.
This one is now based on top of both of those and just has the video changes.

Interestingly we are occasionally hitting a failure not of these changes but fract4d/test_fract4d.py

```py
self = <fract4d.test_fract4d.Test testMethod=testFDSite>
...
                nb = 2*4
                bytes = os.read(rfd,nb)
                if len(bytes) < nb:
>                   self.fail("bad message with length %s, value %s" % (len(bytes), bytes))
E                   AssertionError: bad message with length 4, value b'\x03\x00\x00\x00'
fract4d/test_fract4d.py:573: AssertionError

**Pull request merged**
